import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sanity Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-violet-600 text-2xl underline'>Sanity Social App</h1>'
      
    </>
  )
}
